---
# oVirt API
ovirt_engine_fqdn: "ovirt.engatwork.com"
ovirt_engine_user: "admin@ovirt@internalsso"
ovirt_engine_password: "unix"
ovirt_engine_url: "https://{{ ovirt_engine_fqdn }}/ovirt-engine"
ovirt_api_base: "{{ ovirt_engine_url }}/api"

# Storage domain that backs the mgmt-storage VMs (data_lun)
ovirt_data_storage_domain_id: "f1ef667d-65ae-4506-994a-bebe9488e250"
ovirt_data_storage_domain_name: "data_lun"

# Step 2 sizing
root_disk_grow_to_gb: 50
ceph_osd_disk_size_gb: 500
ceph_osd_disk_alias_prefix: "ceph-osd"
