---
# clear_events.yml - Clear all events from oVirt Engine
# Run: ansible-playbook -i inventory.ini clear_events.yml
#
# Note: oVirt API doesn't support bulk event deletion.
# This uses direct database access to truncate the audit_log table.

- name: Clear All Events
  hosts: engine
  become: true
  gather_facts: false

  vars:
    engine_db_password: "{{ ovirt_engine_db_password }}"

  tasks:
    - name: Clear all events from audit_log table
      ansible.builtin.command:
        cmd: psql -U engine -d engine -h localhost -c "TRUNCATE TABLE audit_log CASCADE;"
      environment:
        PGPASSWORD: "{{ engine_db_password }}"

    - name: Display result
      ansible.builtin.debug:
        msg: "All events cleared from oVirt Engine"
