# mgmt-storage k8s cluster (already bootstrapped 89d ago)
# Fedora 41 Cloud · k8s 1.31.4 · Cilium CNI · OLM
# Step 2 target: grow root disk, attach Ceph OSD data disk.

[mgmt_storage]
mgmt-storage-01  ansible_host=10.10.4.100  ovirt_vm_id=d95909e1-6d13-4854-8df4-1e9a1123577d  root_disk_id=44d92703-5100-4253-874e-76d51320f649
mgmt-storage-02  ansible_host=10.10.4.101  ovirt_vm_id=4519c825-e2e2-4cb4-8d9e-fc6e735288a4  root_disk_id=7556f7c2-bc96-4aa0-82e8-4fc9e04d8035
mgmt-storage-03  ansible_host=10.10.4.102  ovirt_vm_id=8d7aacec-82a6-4cde-a8a6-085995dd1059  root_disk_id=178dea72-ab9e-4dec-b581-8d72b8588fc4

[mgmt_storage:vars]
ansible_user=root
ansible_password=unix

[localhost_group]
localhost ansible_connection=local
